const env = `
PORT=3000
DATABASE_URL=mongodb://localhost:27017/
JWT_SECRET=your_jwt_secret
`;

const envExample: string = `# .env.example
PORT=
DATABASE_URL=
JWT_SECRET=
`;

const gitignore: string = `
# Dependencies
node_modules/

# Compiled output
dist/

# TypeScript
*.tsbuildinfo

# Environment variables
.env
.env.local

# OS files
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*
`;

const eslint: string = `{
  "env": {
    "node": true,
    "es2021": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": 12
  },
  "rules": {}
}
`;

const readmeTemplate: string = `# {{project-name}}

Express application generated by **[express-jetstart](https://github.com/AvusalaChetan/express-jetstart-CLI)** ⚡

> **Love this tool?** Give it a ⭐ on [GitHub](https://github.com/AvusalaChetan/express-jetstart-CLI) and share it with other developers!

---

## Getting Started

### Install Dependencies

\`\`\`bash
npm install
\`\`\`

### Environment Setup

Your \`.env\` file is ready. Update it as needed:

\`\`\`env
PORT=3000
NODE_ENV=development
\`\`\`

### Run the Application

**Development:**

\`\`\`bash
npm run dev
\`\`\`

**Production:**

\`\`\`bash
npm start
\`\`\`

Server runs at \`http://localhost:3000\` 🚀

---

## Project Structure

\`\`\`
{{project-name}}/
├── src/
│   ├── controllers/    # Request handlers
│   ├── routes/         # API routes
│   ├── models/         # Database models
│   ├── middlewares/    # Custom middleware
│   ├── utils/          # Utility functions
│   ├── config/         # App configuration
│   └── services/       # Business logic
├── public/             # Static files
├── server.js or server.ts
└── .env
\`\`\`

---

## Next Steps

1. ✅ Define routes in \`src/routes/\`
2. ✅ Add controllers in \`src/controllers/\`
3. ✅ Create models in \`src/models/\`
4. ✅ Configure middleware as needed

---

## Loved express-jetstart?

- ⭐ [Star it on GitHub](https://github.com/AvusalaChetan/express-jetstart-CLI)
- 🐛 [Report issues](https://github.com/AvusalaChetan/express-jetstart-CLI/issues)
- 💡 [Suggest features](https://github.com/AvusalaChetan/express-jetstart-CLI/issues)
- 📢 Share it with fellow developers!

---

**Scaffolded with ❤️ by [express-jetstart](https://github.com/AvusalaChetan/express-jetstart-CLI)**
`;

export {env, envExample, gitignore, eslint, readmeTemplate};

