export const ejsTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= title %></title>
</head>
<body>
  <h1>Welcome to <%= projectName %> 🚀</h1>
  <p>Express application generated by express-jetstart</p>
</body>
</html>
`;

export const pugTemplate = `doctype html
html(lang="en")
  head
    meta(charset="UTF-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= title
  body
    h1 Welcome to #{projectName} 🚀
    p Express application generated by express-jetstart
`;

export const hbsTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
</head>
<body>
  <h1>Welcome to {{projectName}} 🚀</h1>
  <p>Express application generated by express-jetstart</p>
</body>
</html>
`;
